"""
extraction.py
-------------
LLM-based extraction pipeline for Zoe.Logos-Graph.

Usage:
    python -m src.extraction --input data/raw/abstracts.json --output data/processed/
    python -m src.extraction --input data/raw/abstracts.json --mock
    python -m src.extraction --input data/raw/abstracts.json --config configs/custom.yaml
"""

from __future__ import annotations

import json
import sys
import time
import argparse
from pathlib import Path
from typing import List, Optional, Tuple

from src.config import ZoeConfig, load_config
from src.prompts import SYSTEM_PROMPT, build_extraction_prompt
from src.schema import PaperRecord
from src.validation import validate_record, soft_checks


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------

def get_client():
    import anthropic
    return anthropic.Anthropic()


# ---------------------------------------------------------------------------
# Mock extractor
# ---------------------------------------------------------------------------

def mock_extract(paper_id: str, title: str, abstract: str) -> str:
    """Return a minimal valid JSON record without calling the API."""
    return json.dumps({
        "paper_id": paper_id,
        "title": title,
        "year": None,
        "species_common_name": "unknown",
        "species_scientific_name": "unknown",
        "taxonomic_family": "unknown",
        "developmental_stage": "unknown",
        "communication_domain": "unknown",
        "vocalisation_type": [],
        "behavioural_context": [],
        "putative_function": [],
        "analysis_method": [],
        "main_outcome": "Mock extraction — not a real result.",
        "dataset_or_recording_available": "unknown",
        "dataset_name": None,
        "notes_uncertainty": "Generated by mock extractor for pipeline testing.",
    })


# ---------------------------------------------------------------------------
# Single record extraction
# ---------------------------------------------------------------------------

def extract_record(
    paper_id: str,
    title: str,
    abstract: str,
    cfg: ZoeConfig,
    client=None,
    mock: bool = False,
) -> Tuple[Optional[PaperRecord], str, List[str]]:
    """
    Extract a single paper record from an abstract.

    cfg is passed explicitly so the caller controls which config is active.

    Returns:
        (record, raw_json, errors)
    """
    if mock:
        raw = mock_extract(paper_id, title, abstract)
        parsed = json.loads(raw)
        record, errors = validate_record(parsed)
        return record, raw, errors

    prompt = build_extraction_prompt(paper_id=paper_id, title=title, abstract=abstract)
    raw = ""
    errors: List[str] = []

    for attempt in range(1, cfg.extraction.retries + 2):
        try:
            response = client.messages.create(
                model=cfg.extraction.model,
                max_tokens=cfg.extraction.max_tokens,
                system=SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}],
            )
            raw = response.content[0].text.strip()

            if raw.startswith("```"):
                raw = "\n".join(
                    line for line in raw.splitlines()
                    if not line.strip().startswith("```")
                ).strip()

            parsed = json.loads(raw)
            record, errors = validate_record(parsed)

            if record:
                return record, raw, []
            else:
                print(f"  [attempt {attempt}] Validation failed for {paper_id}: {errors}")

        except json.JSONDecodeError as e:
            print(f"  [attempt {attempt}] JSON parse error for {paper_id}: {e}")
            errors = [f"JSONDecodeError: {e}"]
        except Exception as e:
            print(f"  [attempt {attempt}] Error for {paper_id}: {e}")
            errors = [f"Error: {e}"]
            time.sleep(2 ** attempt)

    return None, raw, errors


# ---------------------------------------------------------------------------
# Batch extraction
# ---------------------------------------------------------------------------

def extract_corpus(
    abstracts: List[dict],
    output_dir: Path,
    cfg: ZoeConfig,
    mock: bool = False,
) -> dict:
    """
    Extract all records from a list of abstract dicts.

    cfg is passed explicitly — no module-level state.

    Each item must have: paper_id, title, abstract.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    client = None if mock else get_client()

    valid_records: List[dict] = []
    failed_records: List[dict] = []
    log_entries: List[dict] = []

    total = len(abstracts)
    mode_label = "mock" if mock else cfg.extraction.model
    print(f"\nStarting extraction: {total} abstracts | mode={mode_label}\n")

    for i, item in enumerate(abstracts, 1):
        paper_id = item.get("paper_id", f"paper_{i:03d}")
        title = item.get("title", "")
        abstract = item.get("abstract", "")

        print(f"[{i}/{total}] {paper_id} — {title[:60]}...")

        record, raw_json, errors = extract_record(
            paper_id=paper_id,
            title=title,
            abstract=abstract,
            cfg=cfg,
            client=client,
            mock=mock,
        )

        if record:
            warnings = soft_checks(record)
            valid_records.append(record.model_dump())
            log_entries.append({"paper_id": paper_id, "status": "valid", "warnings": warnings})
            print(f"  {'⚠  ' + str(warnings) if warnings else '✓  OK'}")
        else:
            failed_records.append({
                "paper_id": paper_id,
                "title": title,
                "errors": errors,
                "raw_output": raw_json,
            })
            log_entries.append({"paper_id": paper_id, "status": "failed", "errors": errors})
            print(f"  ✗  FAILED: {errors}")

        if i < total and not mock:
            time.sleep(cfg.extraction.delay)

    (output_dir / "extracted.json").write_text(
        json.dumps(valid_records, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "failed.json").write_text(
        json.dumps(failed_records, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (output_dir / "extraction_log.json").write_text(
        json.dumps(log_entries, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    summary = {
        "total": total,
        "valid": len(valid_records),
        "failed": len(failed_records),
        "success_rate": round(len(valid_records) / total, 3) if total else 0,
        "mode": mode_label,
    }

    print(f"\n{'='*50}")
    print(f"Extraction complete")
    print(f"  Valid:   {summary['valid']}/{summary['total']}")
    print(f"  Failed:  {summary['failed']}/{summary['total']}")
    print(f"  Rate:    {summary['success_rate']:.1%}")
    print(f"  Output:  {output_dir}")
    print(f"{'='*50}\n")

    return summary


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Run Zoe.Logos-Graph extraction pipeline.")
    parser.add_argument("--input", required=True, help="Path to abstracts JSON file.")
    parser.add_argument("--output", default=None, help="Output directory (overrides config).")
    parser.add_argument("--mock", action="store_true", help="Run without API calls.")
    parser.add_argument("--config", default=None, help="Path to a custom config.yaml.")
    args = parser.parse_args()

    # Load config — always fresh, never stale module-level state
    cfg = load_config(args.config)

    output_dir = Path(args.output) if args.output else cfg.paths.processed

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        sys.exit(1)

    abstracts = json.loads(input_path.read_text(encoding="utf-8"))
    if isinstance(abstracts, dict):
        abstracts = [abstracts]

    extract_corpus(abstracts=abstracts, output_dir=output_dir, cfg=cfg, mock=args.mock)


if __name__ == "__main__":
    main()
